### PR TITLE
fix: pass options to silence warning

### LINKED ISSUE #207: (!) Plugin commonjs--resolver: It appears a plugin has implemented a "resolveId" hook that uses "this.resolve" without forwarding the third "options" parameter of "resolveId"
After upgrading from  `7.1.2` to `7.1.3` I get the following warning when using rollup:

> (!) Plugin commonjs--resolver: It appears a plugin has implemented a "resolveId" hook that uses "this.resolve" without forwarding the third "options" parameter of "resolveId". This is problematic as it can lead to wrong module resolutions especially for the node-resolve plugin and in certain cases cause early exit errors for the commonjs plugin.
> In rare cases, this warning can appear if the same file is both imported and required from the same mixed ES/CommonJS module, in which case it can be ignored.

I'm not sure if this is caused by `rollup-plugin-svelte` itself or a side effect from an other plugin. Any idea how to pinpoint this? Can it be casused by this commit https://github.com/sveltejs/rollup-plugin-svelte/commit/3be2d583515f2c63d43385179339946178563bd7?

### PR DESCRIPTION
**Pull request by dummdidumm**
fixes #207

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -95,7 +95,7 @@ module.exports = function (options = {}) {
 				return path.resolve(dir, pkg.svelte);
 			}
 
-			const resolved = await this.resolve(importee, importer, { skipSelf: true });
+			const resolved = await this.resolve(importee, importer, { skipSelf: true, ...options });
```
Comment (dominikg) [inline index.js:98]: not sure if legal to pass in from the outside, but to prevent endless loop it would be better to put skipSelf: true after the spread
```suggestion
			const resolved = await this.resolve(importee, importer, { ...options, skipSelf: true });
```

Comment (dominikg) [reply index.js:98]: looks like Lukas himself suggested putting it in front, so feel free to ignore this https://github.com/lightyen/typescript-paths/issues/3#issue-1206676674

**Review by dominikg — APPROVED** [review]
